### ISSUE TITLE
Image and Template Commands defaulting to .NET 5 - Breaks Build

### ISSUE THREAD

**Issue by dalenewman** [denolfe/blog-code-samples#12]
Looks like the release of .net 5 may make it so your blog post is out of date.  

There might be a way to make this work for .NET 5, but to get it to work for .Net Core 3.1:

1. Use the `-f netcoreapp3.1` framework flag on the `dotnet new` commands.
2. Change the image to `mcr.microsoft.com/dotnet/core/sdk:3.1` in the *.gitlab-ci.yml* file.
3. Change *../publish* to *./publish* in the *.gitlab-ci.yml* file.

Great blog post!

Thanks

**Comment by denolfe** [comment]
Thanks @dalenewman! I've updated it for .NET 5 👍
